"""Migration registry and tracking.

This module maintains a registry of all available schema migrations
and provides utilities for selective migration execution.
"""

from typing import Callable, List

from sqlalchemy.engine import Connection

from .schema_updates import (
    add_feature_access_table,
    add_groups_column_to_users,
    add_invocation_index_column,
    add_is_sub_agent_column,
    add_mcp_server_visibility_fields,
    add_navigation_feature_access,
    add_node_executions_graph_status_index,
    add_review_iteration_column,
    add_thread_id_column,
    add_token_counting_columns,
    add_trace_viewer_columns,
    add_websocket_execution_id_column,
    add_workflow_id_column,
    add_workflow_template_name_column,
    adjust_embedding_vector_dimension,
    convert_category_to_json_array,
    create_agent_review_states_table,
    create_agent_templates_table,
    create_execution_files_table,
    create_oauth_tables,
    create_subagent_iteration_states_table,
    create_system_settings_table,
    create_user_api_tokens_table,
    create_user_external_services_table,
    drop_workflow_template_estimated_time_column,
    enable_pgvector_extension,
    migrate_template_categories,
    seed_feature_access,
    create_groups_table,
    create_group_memberships_table,
    add_visible_to_groups_column,
    seed_administrators_group,
    add_model_deployment_pricing_columns,
    add_cron_input_column,
    add_cron_schedule_columns,
    add_user_role_column,
    add_system_user_role,
    add_workflow_http_trigger_token,
    create_system_external_services_table,
    migrate_user_external_services_schema,
    add_collection_embedding_deployment_id,
    add_document_embedding_cost_columns,
    add_evaluation_run_id_column,
    add_evaluation_regression_ack_column,
    add_evaluation_dataset_target_and_tags_columns,
    add_workflow_auto_eval_config_column,
    add_trigger_type_column,
    create_execution_feedback_table,
    add_node_execution_id_to_feedback,
    create_node_version_index_table,
    add_graph_definition_id_to_evaluation_runs,
    add_graph_definition_id_to_execution_feedback,
    add_node_config_hash_to_node_executions,
    add_evaluation_dataset_workflow_id_column,
    create_test_case_files_table,
    add_dataset_visible_to_groups_column,
    add_recommendation_applied_version_columns,
    add_judge_output_policy_column,
    add_visible_to_groups_to_datasource_connections,
    ensure_api_endpoints_jsonb_columns,
    update_api_endpoint_name_uniqueness,
    add_api_endpoint_service_type_and_health_columns,
    add_search_count_to_collections,
    add_execution_history_performance_indexes,
    add_evaluations_navigation_feature_access,
    ensure_datasource_connections_jsonb_visible_to_groups,
    add_execution_list_performance_indexes,
    create_chat_sessions_table,
    add_chat_session_id_to_graph_executions,
    add_chat_session_id_to_conversation_memories,
    add_chat_navigation_feature_access,
    seed_wiki_pages,
    create_wiki_images_table,
    add_wiki_search_vector_index,
    create_tutorial_progress_table,
    create_guardrail_violations_table,
    create_guardrail_policy_versions_table,
    create_guardrail_violation_feedback_table,
    add_is_builtin_column_to_guardrail_policies,
    add_guardrail_policy_versioning_columns,
    fix_guardrail_policy_versions_schema,
    migrate_inline_guardrails_to_policies,
    add_visible_to_groups_to_guardrail_policies,
    create_group_external_service_configs_table,
    create_group_external_service_assignments_table,
    add_mcp_shared_with_groups_column,
    add_guardrails_navigation_feature_access,
    create_scope_rejection_log_table,
    seed_api_tokens_restrict_feature_access,
    migrate_pat_scopes_to_v2,
    flatten_behavioral_guardrails_config,
    create_workflow_assets_table,
    sanitize_existing_wiki_content,
    create_tool_security_policies_table,
    create_email_ownership_tables,
    rename_blocked_ip_ranges_to_allowed_ip_ranges,
    sync_fixed_ips_from_env,
    add_fixed_ips_column_to_tool_security_policies,
    migrate_legacy_cidr_ssrf_policies,
    seed_tool_security_policies_defaults,
    add_groundedness_columns_to_chat_response_scores,
)

# Type alias for migration function
MigrationFunc = Callable[[Connection], None]


class Migration:
    """Represents a single database migration.

    Attributes:
        name: Human-readable migration name
        func: Migration function to execute
        enabled: Whether this migration should be run
    """

    def __init__(self, name: str, func: MigrationFunc, enabled: bool = True):
        """Initialize migration.

        Args:
            name: Human-readable migration name
            func: Migration function to execute
            enabled: Whether this migration should be run
        """
        self.name = name
        self.func = func
        self.enabled = enabled

    def execute(self, conn: Connection) -> None:
        """Execute the migration.

        Args:
            conn: Database connection
        """
        if self.enabled:
            self.func(conn)


# Registry of all available migrations
# Order matters - migrations run in the order listed
MIGRATIONS: List[Migration] = [
    Migration(
        name="enable_pgvector_extension",
        func=enable_pgvector_extension,
        enabled=True,
    ),
    Migration(
        name="adjust_embedding_vector_dimension",
        func=adjust_embedding_vector_dimension,
        enabled=True,
    ),
    Migration(
        name="add_thread_id_column",
        func=add_thread_id_column,
        enabled=True,
    ),
    Migration(
        name="add_is_sub_agent_column",
        func=add_is_sub_agent_column,
        enabled=True,
    ),
    Migration(
        name="add_token_counting_columns",
        func=add_token_counting_columns,
        enabled=True,
    ),
    Migration(
        name="add_websocket_execution_id_column",
        func=add_websocket_execution_id_column,
        enabled=True,
    ),
    Migration(
        name="add_trace_viewer_columns",
        func=add_trace_viewer_columns,
        enabled=True,
    ),
    Migration(
        name="add_workflow_id_column",
        func=add_workflow_id_column,
        enabled=True,
    ),
    Migration(
        name="create_user_api_tokens_table",
        func=create_user_api_tokens_table,
        enabled=True,
    ),
    Migration(
        name="create_agent_templates_table",
        func=create_agent_templates_table,
        enabled=True,
    ),
    Migration(
        name="add_workflow_template_name_column",
        func=add_workflow_template_name_column,
        enabled=True,
    ),
    Migration(
        name="drop_workflow_template_estimated_time_column",
        func=drop_workflow_template_estimated_time_column,
        enabled=True,
    ),
    Migration(
        name="convert_category_to_json_array",
        func=convert_category_to_json_array,
        enabled=True,
    ),
    Migration(
        name="create_oauth_tables",
        func=create_oauth_tables,
        enabled=True,
    ),
    Migration(
        name="create_agent_review_states_table",
        func=create_agent_review_states_table,
        enabled=True,
    ),
    Migration(
        name="create_user_external_services_table",
        func=create_user_external_services_table,
        enabled=True,
    ),
    Migration(
        name="add_mcp_server_visibility_fields",
        func=add_mcp_server_visibility_fields,
        enabled=True,
    ),
    Migration(
        name="add_groups_column_to_users",
        func=add_groups_column_to_users,
        enabled=True,
    ),
    Migration(
        name="add_feature_access_table",
        func=add_feature_access_table,
        enabled=True,
    ),
    Migration(
        name="seed_feature_access",
        func=seed_feature_access,
        enabled=True,
    ),
    Migration(
        name="add_navigation_feature_access",
        func=add_navigation_feature_access,
        enabled=True,
    ),
    Migration(
        name="migrate_template_categories",
        func=migrate_template_categories,
        enabled=True,
    ),
    Migration(
        name="add_review_iteration_column",
        func=add_review_iteration_column,
        enabled=True,
    ),
    Migration(
        name="add_node_executions_graph_status_index",
        func=add_node_executions_graph_status_index,
        enabled=True,
    ),
    Migration(
        name="create_execution_files_table",
        func=create_execution_files_table,
        enabled=True,
    ),
    Migration(
        name="create_subagent_iteration_states_table",
        func=create_subagent_iteration_states_table,
        enabled=True,
    ),
    Migration(
        name="add_invocation_index_column",
        func=add_invocation_index_column,
        enabled=True,
    ),
    Migration(
        name="create_groups_table",
        func=create_groups_table,
        enabled=True,
    ),
    Migration(
        name="create_group_memberships_table",
        func=create_group_memberships_table,
        enabled=True,
    ),
    Migration(
        name="add_visible_to_groups_column",
        func=add_visible_to_groups_column,
        enabled=True,
    ),
    Migration(
        name="seed_administrators_group",
        func=seed_administrators_group,
        enabled=True,
    ),
    Migration(
        name="add_model_deployment_pricing_columns",
        func=add_model_deployment_pricing_columns,
        enabled=True,
    ),
    Migration(
        name="add_cron_schedule_columns",
        func=add_cron_schedule_columns,
        enabled=True,
    ),
    Migration(
        name="add_cron_input_column",
        func=add_cron_input_column,
        enabled=True,
    ),
    Migration(
        name="add_user_role_column",
        func=add_user_role_column,
        enabled=True,
    ),
    Migration(
        name="add_system_user_role",
        func=add_system_user_role,
        enabled=True,
    ),
    Migration(
        name="add_workflow_http_trigger_token",
        func=add_workflow_http_trigger_token,
        enabled=True,
    ),
    Migration(
        name="create_system_settings_table",
        func=create_system_settings_table,
        enabled=True,
    ),
    Migration(
        name="create_system_external_services_table",
        func=create_system_external_services_table,
        enabled=True,
    ),
    Migration(
        name="migrate_user_external_services_schema",
        func=migrate_user_external_services_schema,
        enabled=True,
    ),
    Migration(
        name="add_collection_embedding_deployment_id",
        func=add_collection_embedding_deployment_id,
        enabled=True,
    ),
    Migration(
        name="add_document_embedding_cost_columns",
        func=add_document_embedding_cost_columns,
        enabled=True,
    ),
    Migration(
        name="add_evaluation_run_id_column",
        func=add_evaluation_run_id_column,
        enabled=True,
    ),
    Migration(
        name="add_evaluation_regression_ack_column",
        func=add_evaluation_regression_ack_column,
        enabled=True,
    ),
    Migration(
        name="add_evaluation_dataset_target_and_tags_columns",
        func=add_evaluation_dataset_target_and_tags_columns,
        enabled=True,
    ),
    Migration(
        name="add_workflow_auto_eval_config_column",
        func=add_workflow_auto_eval_config_column,
        enabled=True,
    ),
    Migration(
        name="add_trigger_type_column",
        func=add_trigger_type_column,
        enabled=True,
    ),
    Migration(
        name="create_execution_feedback_table",
        func=create_execution_feedback_table,
        enabled=True,
    ),
    Migration(
        name="add_node_execution_id_to_feedback",
        func=add_node_execution_id_to_feedback,
        enabled=True,
    ),
    Migration(
        name="create_node_version_index_table",
        func=create_node_version_index_table,
        enabled=True,
    ),
    Migration(
        name="add_graph_definition_id_to_evaluation_runs",
        func=add_graph_definition_id_to_evaluation_runs,
        enabled=True,
    ),
    Migration(
        name="add_graph_definition_id_to_execution_feedback",
        func=add_graph_definition_id_to_execution_feedback,
        enabled=True,
    ),
    Migration(
        name="add_node_config_hash_to_node_executions",
        func=add_node_config_hash_to_node_executions,
        enabled=True,
    ),
    Migration(
        name="add_evaluation_dataset_workflow_id_column",
        func=add_evaluation_dataset_workflow_id_column,
        enabled=True,
    ),
    Migration(
        name="create_test_case_files_table",
        func=create_test_case_files_table,
        enabled=True,
    ),
    Migration(
        name="add_dataset_visible_to_groups_column",
        func=add_dataset_visible_to_groups_column,
        enabled=True,
    ),
    Migration(
        name="add_recommendation_applied_version_columns",
        func=add_recommendation_applied_version_columns,
        enabled=True,
    ),
    Migration(
        name="add_judge_output_policy_column",
        func=add_judge_output_policy_column,
        enabled=True,
    ),
    Migration(
        name="add_visible_to_groups_to_datasource_connections",
        func=add_visible_to_groups_to_datasource_connections,
        enabled=True,
    ),
    Migration(
        name="ensure_api_endpoints_jsonb_columns",
        func=ensure_api_endpoints_jsonb_columns,
        enabled=True,
    ),
    Migration(
        name="update_api_endpoint_name_uniqueness",
        func=update_api_endpoint_name_uniqueness,
        enabled=True,
    ),
    Migration(
        name="add_api_endpoint_service_type_and_health_columns",
        func=add_api_endpoint_service_type_and_health_columns,
        enabled=True,
    ),
    Migration(
        name="add_search_count_to_collections",
        func=add_search_count_to_collections,
        enabled=True,
    ),
    Migration(
        name="add_execution_history_performance_indexes",
        func=add_execution_history_performance_indexes,
        enabled=True,
    ),
    Migration(
        name="ensure_datasource_connections_jsonb_visible_to_groups",
        func=ensure_datasource_connections_jsonb_visible_to_groups,
        enabled=True,
    ),
    Migration(
        name="add_evaluations_navigation_feature_access",
        func=add_evaluations_navigation_feature_access,
        enabled=True,
    ),
    Migration(
        name="add_execution_list_performance_indexes",
        func=add_execution_list_performance_indexes,
        enabled=True,
    ),
    Migration(
        name="create_chat_sessions_table",
        func=create_chat_sessions_table,
        enabled=True,
    ),
    Migration(
        name="add_chat_session_id_to_graph_executions",
        func=add_chat_session_id_to_graph_executions,
        enabled=True,
    ),
    Migration(
        name="add_chat_session_id_to_conversation_memories",
        func=add_chat_session_id_to_conversation_memories,
        enabled=True,
    ),
    Migration(
        name="add_chat_navigation_feature_access",
        func=add_chat_navigation_feature_access,
        enabled=True,
    ),
    Migration(
        name="seed_wiki_pages",
        func=seed_wiki_pages,
        enabled=True,
    ),
    Migration(
        name="create_wiki_images_table",
        func=create_wiki_images_table,
        enabled=True,
    ),
    Migration(
        name="add_wiki_search_vector_index",
        func=add_wiki_search_vector_index,
        enabled=True,
    ),
    Migration(
        name="create_tutorial_progress_table",
        func=create_tutorial_progress_table,
        enabled=True,
    ),
    Migration(
        name="create_guardrail_violations_table",
        func=create_guardrail_violations_table,
        enabled=True,
    ),
    Migration(
        name="create_guardrail_policy_versions_table",
        func=create_guardrail_policy_versions_table,
        enabled=True,
    ),
    Migration(
        name="create_guardrail_violation_feedback_table",
        func=create_guardrail_violation_feedback_table,
        enabled=True,
    ),
    Migration(
        name="add_is_builtin_column_to_guardrail_policies",
        func=add_is_builtin_column_to_guardrail_policies,
        enabled=True,
    ),
    Migration(
        name="add_guardrail_policy_versioning_columns",
        func=add_guardrail_policy_versioning_columns,
        enabled=True,
    ),
    Migration(
        name="fix_guardrail_policy_versions_schema",
        func=fix_guardrail_policy_versions_schema,
        enabled=True,
    ),
    Migration(
        name="migrate_inline_guardrails_to_policies",
        func=migrate_inline_guardrails_to_policies,
        enabled=True,
    ),
    Migration(
        name="add_visible_to_groups_to_guardrail_policies",
        func=add_visible_to_groups_to_guardrail_policies,
        enabled=True,
    ),
    Migration(
        name="create_group_external_service_configs_table",
        func=create_group_external_service_configs_table,
        enabled=True,
    ),
    Migration(
        name="create_group_external_service_assignments_table",
        func=create_group_external_service_assignments_table,
        enabled=True,
    ),
    Migration(
        name="add_mcp_shared_with_groups_column",
        func=add_mcp_shared_with_groups_column,
        enabled=True,
    ),
    Migration(
        name="add_guardrails_navigation_feature_access",
        func=add_guardrails_navigation_feature_access,
        enabled=True,
    ),
    Migration(
        name="create_scope_rejection_log_table",
        func=create_scope_rejection_log_table,
        enabled=True,
    ),
    Migration(
        name="seed_api_tokens_restrict_feature_access",
        func=seed_api_tokens_restrict_feature_access,
        enabled=True,
    ),
    Migration(
        name="migrate_pat_scopes_to_v2",
        func=migrate_pat_scopes_to_v2,
        enabled=True,
    ),
    Migration(
        name="flatten_behavioral_guardrails_config",
        func=flatten_behavioral_guardrails_config,
        enabled=True,
    ),
    Migration(
        name="create_workflow_assets_table",
        func=create_workflow_assets_table,
        enabled=True,
    ),
    Migration(
        name="sanitize_existing_wiki_content",
        func=sanitize_existing_wiki_content,
        enabled=True,
    ),
    Migration(
        name="create_tool_security_policies_table",
        func=create_tool_security_policies_table,
        enabled=True,
    ),
    Migration(
        name="create_email_ownership_tables",
        func=create_email_ownership_tables,
        enabled=True,
    ),
    Migration(
        name="rename_blocked_ip_ranges_to_allowed_ip_ranges",
        func=rename_blocked_ip_ranges_to_allowed_ip_ranges,
        enabled=True,
    ),
    Migration(
        name="add_fixed_ips_column_to_tool_security_policies",
        func=add_fixed_ips_column_to_tool_security_policies,
        enabled=True,
    ),
    Migration(
        name="seed_tool_security_policies_defaults",
        func=seed_tool_security_policies_defaults,
        enabled=True,
    ),
    Migration(
        name="migrate_legacy_cidr_ssrf_policies",
        func=migrate_legacy_cidr_ssrf_policies,
        enabled=True,
    ),
    Migration(
        name="sync_fixed_ips_from_env",
        func=sync_fixed_ips_from_env,
        enabled=True,
    ),
    Migration(
        name="add_groundedness_columns_to_chat_response_scores",
        func=add_groundedness_columns_to_chat_response_scores,
        enabled=True,
    ),
]


def get_enabled_migrations() -> List[Migration]:
    """Get list of enabled migrations.

    Returns:
        List of enabled Migration objects
    """
    return [m for m in MIGRATIONS if m.enabled]


def get_migration_names() -> List[str]:
    """Get list of all migration names.

    Returns:
        List of migration names
    """
    return [m.name for m in MIGRATIONS]
