"""Python workflow exporter.

Orchestrates code generation from a GraphData object into a self-contained
Python file that runs as a standard LangGraph application.
"""

from datetime import datetime, timezone

from backend.models.workflow import GraphData

from .generators.graph_generator import GraphGenerator
from .generators.helpers_generator import HelpersGenerator
from .generators.imports_generator import ImportsGenerator
from .generators.llm_generator import LLMGenerator
from .generators.main_generator import MainGenerator
from .generators.node_generator import NodeGenerator
from .generators.state_generator import StateGenerator
from .generators.tool_generators import ToolGenerators
from .workflow_analyzer import WorkflowAnalyzer


class PythonExporter:
    """Exports a workflow as a self-contained Python file."""

    def __init__(self):
        self.analyzer = WorkflowAnalyzer()
        self.imports_gen = ImportsGenerator()
        self.state_gen = StateGenerator()
        self.helpers_gen = HelpersGenerator()
        self.llm_gen = LLMGenerator()
        self.tool_gen = ToolGenerators()
        self.node_gen = NodeGenerator()
        self.graph_gen = GraphGenerator()
        self.main_gen = MainGenerator()

    def export(self, graph: GraphData) -> str:
        """Export a GraphData object as a self-contained Python file.

        Args:
            graph: The workflow graph definition

        Returns:
            Python source code as a string
        """
        analysis = self.analyzer.analyze(graph)

        sections = []

        # Header
        sections.append(self._generate_header(analysis))

        # Section 1: Imports
        sections.append(self.imports_gen.generate(analysis))

        # Section 2-3: State reducers + WorkflowState
        sections.append(self.state_gen.generate(analysis))

        # Section 4: Helper functions (input building)
        helpers = self.helpers_gen.generate(analysis)
        if helpers:
            sections.append(helpers)

        # Section 5: LLM factory functions
        llm_code = self.llm_gen.generate(analysis)
        if llm_code:
            sections.append(llm_code)

        # Section 6: Tool factory functions
        tool_code = self.tool_gen.generate(analysis)
        if tool_code:
            sections.append(tool_code)

        # Section 7: Node functions
        sections.append(self.node_gen.generate(analysis))

        # Sections 8-9: Routing functions + Graph construction
        sections.append(self.graph_gen.generate(analysis))

        # Sections 10-11: Compile + __main__
        sections.append(self.main_gen.generate(analysis))

        return "\n\n\n".join(s for s in sections if s) + "\n"

    def _generate_header(self, analysis) -> str:
        """Generate the file header with metadata."""
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        name = analysis.workflow_name

        lines = [
            '"""',
            f"Auto-generated LangGraph workflow: {name}",
            f"Generated by Agentic Studio on {timestamp}",
            '"""',
        ]

        # Add required env vars comment
        if analysis.env_vars_required:
            lines.append("")
            lines.append("# Required environment variables:")
            for var, nodes in sorted(analysis.env_vars_required.items()):
                nodes_str = ", ".join(nodes)
                lines.append(f"#   {var}: Used by {nodes_str}")

        # Add warnings for unsupported nodes
        if analysis.unsupported_nodes:
            lines.append("")
            lines.append(
                "# WARNING: The following node types are not supported in export:"
            )
            for node in analysis.unsupported_nodes:
                type_val = (
                    node.type.value if hasattr(node.type, "value") else str(node.type)
                )
                lines.append(f"#   - {node.name} ({type_val})")
            lines.append("# These nodes will raise NotImplementedError at runtime.")

        return "\n".join(lines)
