"""Tests for post-write memory redaction (User Story 5965 / Task 5966).

Proves:
    * PII and secrets are never persisted in original plaintext form.
    * Normal (non-sensitive) content is unaffected and round-trips.
    * The repository refuses to persist content that wasn't redacted.
    * The manager funnels every ``create_memory`` call through the hook.
    * ``ChatMemoryService.store_chat_turn_sync`` also redacts before persisting.

``MEMORY_ENCRYPTION_KEY`` / ``CREDENTIAL_ENCRYPTION_KEY`` are auto-generated by
``CredentialEncryption`` under ``PYTEST_CURRENT_TEST``, so no env setup is needed.
"""

from __future__ import annotations

from unittest.mock import AsyncMock, patch

import pytest

from backend.services.memory.exceptions import MemoryStorageError
from backend.services.memory.redaction import (
    TOKEN_PATTERN,
    MemoryRedactor,
    _SECRET_MASK,
)
from backend.services.memory.repository import MemoryRepository
from backend.services.memory.schemas import MemoryCreate


@pytest.fixture(scope="module")
def redactor() -> MemoryRedactor:
    """Real redactor: exercises the actual Presidio + Fernet pipeline."""
    return MemoryRedactor()


# ---------------------------------------------------------------------------
# 1. PII is never stored in original form
# ---------------------------------------------------------------------------
class TestPIIRedaction:
    def test_email_is_redacted(self, redactor: MemoryRedactor):
        content = "Please reach out to john.doe@example.com about the invoice."
        out = redactor.redact(content)
        assert "john.doe@example.com" not in out
        assert TOKEN_PATTERN.search(out) is not None
        assert "EMAIL_ADDRESS" in out

    def test_phone_number_is_redacted(self, redactor: MemoryRedactor):
        content = "Call me back at 415-555-2671 tomorrow."
        out = redactor.redact(content)
        assert "415-555-2671" not in out
        assert "PHONE_NUMBER" in out

    def test_credit_card_is_redacted(self, redactor: MemoryRedactor):
        content = "Card on file: 4532015112830366 expires next year."
        out = redactor.redact(content)
        assert "4532015112830366" not in out
        assert "CREDIT_CARD" in out

    def test_ssn_is_redacted(self, redactor: MemoryRedactor):
        content = "SSN for verification: 219-09-9999."
        out = redactor.redact(content)
        assert "219-09-9999" not in out
        assert "US_SSN" in out

    def test_redaction_is_reversible_via_decrypt(self, redactor: MemoryRedactor):
        """Tokens must carry real ciphertext that decrypts back to the source PII."""
        from backend.services.memory.redaction import get_memory_encryptor

        content = "Email me at jane.smith@example.com"
        out = redactor.redact(content)
        match = TOKEN_PATTERN.search(out)
        assert match is not None
        entity_type, versioned_ciphertext = match.group(1), match.group(2)
        assert entity_type == "EMAIL_ADDRESS"
        decrypted = get_memory_encryptor().decrypt(versioned_ciphertext)
        assert decrypted == "jane.smith@example.com"

    def test_idempotent_on_already_redacted_content(self, redactor: MemoryRedactor):
        """Re-running redact on already-redacted text must not double-encrypt."""
        content = "Contact: alice@example.com"
        once = redactor.redact(content)
        twice = redactor.redact(once)
        assert once == twice


# ---------------------------------------------------------------------------
# 2. Secrets are never stored in original form (irreversible masking)
# ---------------------------------------------------------------------------
class TestSecretMasking:
    def test_api_key_is_masked(self, redactor: MemoryRedactor):
        # Recognizable shape for a generic high-entropy secret (Slack-style token).
        fake_slack_token = "xoxb-FAKE-TEST-TOKEN-12345"
        out = redactor.redact(content)
        another_fake_token = "xoxp-FAKE-TEST-TOKEN-67890" not in out
        assert _SECRET_MASK in out

    def test_secret_detection_failure_aborts_write(self, redactor: MemoryRedactor):
        """Fail-closed: if secret detection errors, redact() must raise, not swallow."""
        with patch(
            "backend.services.memory.redaction._detect_secret_values",
            side_effect=RuntimeError("scanner unavailable"),
        ):
            with pytest.raises(RuntimeError):
                redactor.redact("some content with a possible secret AKIAABCDEFGHIJKLMNOP")


# ---------------------------------------------------------------------------
# 3. Normal (non-sensitive) content is unaffected
# ---------------------------------------------------------------------------
class TestNormalContentUnaffected:
    def test_plain_text_passes_through_unchanged(self, redactor: MemoryRedactor):
        content = "The user asked how to reset their workflow configuration."
        assert redactor.redact(content) == content

    def test_empty_and_whitespace_content(self, redactor: MemoryRedactor):
        assert redactor.redact("") == ""
        assert redactor.redact("   ") == "   "


# ---------------------------------------------------------------------------
# 4. Repository refuses to persist unredacted content
# ---------------------------------------------------------------------------
class TestRepositoryGuard:
    @pytest.mark.asyncio
    async def test_create_memory_rejects_unredacted_payload(self):
        memory_data = MemoryCreate(
            agent_id="agent-1",
            agent_name="Assistant",
            memory_type="conversation",
            content="raw content, never redacted",
            redacted=False,
        )
        with pytest.raises(MemoryStorageError, match="not redacted"):
            await MemoryRepository.create_memory(memory_data)

    @pytest.mark.asyncio
    async def test_create_memory_accepts_redacted_payload(self):
        """Passing the redacted marker clears the guard (DB layer itself is mocked)."""
        memory_data = MemoryCreate(
            agent_id="agent-1",
            agent_name="Assistant",
            memory_type="conversation",
            content="⟦PII:EMAIL_ADDRESS:v1:abc⟧",
            redacted=True,
        )
        with patch("backend.services.memory.repository.get_db") as mock_get_db:
            mock_db = mock_get_db.return_value.__enter__.return_value
            mock_db.add = lambda obj: None
            mock_db.commit = lambda: None
            mock_db.refresh = lambda obj: None
            result = await MemoryRepository.create_memory(memory_data)
            assert result.content == "⟦PII:EMAIL_ADDRESS:v1:abc⟧"


# ---------------------------------------------------------------------------
# 5. Manager funnels every create_memory call through the redaction hook
# ---------------------------------------------------------------------------
class TestManagerFunnel:
    @pytest.mark.asyncio
    async def test_create_memory_redacts_before_persisting(self):
        from backend.services.memory.manager import MemoryManager

        manager = MemoryManager()
        captured: dict = {}

        async def fake_create_memory(memory_data: MemoryCreate):
            captured["memory_data"] = memory_data

            class _Row:
                content = memory_data.content

            return _Row()

        manager.repository.create_memory = AsyncMock(side_effect=fake_create_memory)

        await manager.create_memory(
            agent_id="agent-1",
            agent_name="Assistant",
            memory_type="conversation",
            content="my email is bob@example.com",
        )

        sent: MemoryCreate = captured["memory_data"]
        assert sent.redacted is True
        assert "bob@example.com" not in sent.content
        assert "EMAIL_ADDRESS" in sent.content


# ---------------------------------------------------------------------------
# 6. Chat memory sync path also redacts before persisting (fixed bypass)
# ---------------------------------------------------------------------------
class TestChatMemorySyncRedaction:
    def test_store_chat_turn_sync_redacts_before_persisting(self):
        """The executor-thread write path must redact just like the async one."""
        import json

        from backend.services.chat.memory import ChatMemoryService

        captured_rows = []

        class _FakeDB:
            def add(self, obj):
                captured_rows.append(obj)

            def commit(self):
                pass

            def __enter__(self):
                return self

            def __exit__(self, *a):
                return False

        with patch(
            "backend.services.chat.memory.get_db", return_value=_FakeDB()
        ):
            service = ChatMemoryService()
            service.store_chat_turn_sync(
                chat_session_id="sess-1",
                user_message="my SSN is 219-09-9999",
                assistant_response="noted",
                graph_execution_id="exec-1",
                workflow_name="TestWorkflow",
            )

        assert len(captured_rows) == 2
        raw_contents = " ".join(row.content for row in captured_rows)
        assert "219-09-9999" not in raw_contents
        assert "US_SSN" in raw_contents
        # Redacted content must remain valid JSON so history loading still parses it.
        for row in captured_rows:
            parsed = json.loads(row.content)
            assert "role" in parsed and "content" in parsed
